# Generated by Django 5.2.7 on 2025-11-04 07:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="statistics",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("total_tasks_completed", models.PositiveIntegerField(default=0)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("current_level", models.PositiveIntegerField(default=1)),
                ("friend_count", models.PositiveIntegerField(default=0)),
                ("challenges_won", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Statistic",
                "verbose_name_plural": "User Statistics",
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "criteria",
                    models.JSONField(help_text="JSON with criteria configuration, e.g., {'required_count': 7, 'type': 'consecutive_days'}"),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("task_count", "Task Count"),
                            ("streak", "Streak"),
                            ("level", "Level"),
                            ("friend_count", "Friend Count"),
                            ("challenge", "Challenge"),
                        ],
                        default="task_count",
                        max_length=20,
                    ),
                ),
                ("reward_xp", models.PositiveIntegerField(default=0)),
                ("reward_coins", models.PositiveIntegerField(default=0)),
                ("icon", models.URLField(blank=True, default="")),
                (
                    "rarity",
                    models.CharField(
                        choices=[("common", "Common"), ("rare", "Rare"), ("epic", "Epic"), ("legendary", "Legendary")],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["criteria_type", "is_active"], name="achievement_criteri_67350a_idx"),
                    models.Index(fields=["rarity"], name="achievement_rarity_66025b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "progress",
                    models.DecimalField(decimal_places=2, default=0.0, help_text="Progress percentage (0.00 to 100.00)", max_digits=5),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_achievements", to="achievements.achievement"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_achievements", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "ordering": ["-unlocked_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_completed"], name="achievement_user_id_7738d9_idx"),
                    models.Index(fields=["achievement", "is_completed"], name="achievement_achieve_076685_idx"),
                ],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
